# Generated by Django 3.0.8 on 2021-02-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile', models.FileField(upload_to='')),
                ('unique_code', models.CharField(default='123456@codeathon', max_length=200)),
                ('annotation_result', models.FileField(upload_to='')),
            ],
        ),
    ]
